### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by RcNgtm** [RcNgtm/furima-37770#21]
# URL
https://furima-37770.herokuapp.com/

# Basic認証のIDとパスワード
admin
37770

# 出品者用のメールアドレスとパスワード
test1@furima
testtest1

# 購入者用のメールアドレスとパスワード
test2@frima
testtest2

**Comment by motomuun** [comment]
@RcNgtm さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品一覧表示機能の確認**

- [ ] **商品が出品されていない状態では、ダミーの商品情報が表示されること**
こちらの確認のため、画像を含むデータを一度リセットした状態で提出をお願いします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by RcNgtm** [comment]
確認ありがとうございます。
データベースリセットして提出していたかと思うのですが、
```
heroku run DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rails db:drop db:create db:migrate
```
こちらの実行では不足があったということでしょうか？
また、リセットした場合は再度ユーザーの登録が必要でしょうか？
よろしくお願いいたします

**Comment by snkw-works** [comment]
@RcNgtm さん、お待たせいたしました。お問い合わせいただきありがとうございます。
再度確認したところ、出品がない状態でダミー画像が正しく表示されていることが確認できました。
この度はお問い合わせのお手数をおかけしてしまい大変申し訳ございませんでした。

全ての項目が正常に動作することが確認できましたので、**LGTM** とさせていただきます。
おめでとうございます！

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/curriculums/7106

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/54050089/164166779-9eca4a1e-955a-4d55-bfa3-c0ff25e73e87.png)
